name: NodeJS with Snowpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: ./build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: ./build
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
